### ISSUE TITLE
Which Ruby version?

### ISSUE THREAD

**Issue by programmarchy** [simonneutert/sinatras-skeleton#3]
Hello. I am loving this setup! Quick question for you -- which version of Ruby are you using? I see 2.5.1 in the Gemfile but 2.4.4 in the .ruby-version.

Did you happen to run into this bug with version 2.5.1?

https://github.com/sinatra/sinatra/issues/1478

Thanks!

**Comment by simonneutert** [comment]
@programmarchy I updated the ruby version and bumped the gem versions to newest, if you have problems installing pg >= 1.0 see this:

* http://www.simon-neutert.de/2018/pg-gem-with-postgres-app-on-mac/ << adapt gem version accordingly

works for me here locally now 👍 please let me know if everything is okay on your side 😄

**Comment by simonneutert** [comment]
okay, all is fixed now. removed the magic comment `# frozen_string_literal: true`, this is what broke the code.

please pull the code again and tell me if this has fixed it for you 👍

**Comment by programmarchy** [comment]
Ah, it's kind of a bummer we can't use frozen string literals because they do improve performance.

Pretty sure this is a bug in sinatra, not sinatras-skeleton. I'm hoping to get my pull request through so hopefully we can upgrade sinatra and start using frozen string literals again.

Cheers! 🍻

**Comment by simonneutert** [comment]
Thank you for sorting this out with me! If you want to contribute to this project, please feel free to do so 😀 👍
